const ErrorCodes = {
  // Authentication & Authorization
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_TOKEN_REUSE: 'AUTH_TOKEN_REUSE',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Resource
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',

  ORGANIZER_REQUEST_NOT_FOUND: 'ORGANIZER_REQUEST_NOT_FOUND',
  ORGANIZER_REQUEST_ALREADY_REVIEWED: 'ORGANIZER_REQUEST_ALREADY_REVIEWED',
  ORGANIZER_REQUEST_PENDING_EXISTS: 'ORGANIZER_REQUEST_PENDING_EXISTS',
  ORGANIZER_REQUEST_ALREADY_ORGANIZER: 'ORGANIZER_REQUEST_ALREADY_ORGANIZER',

  FEEDBACK_NOT_ELIGIBLE: 'FEEDBACK_NOT_ELIGIBLE',
  FEEDBACK_ALREADY_EXISTS: 'FEEDBACK_ALREADY_EXISTS',
  FEEDBACK_EVENT_NOT_FOUND: 'FEEDBACK_EVENT_NOT_FOUND',

  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_ITEMS: 'ORDER_INVALID_ITEMS',
  ORDER_TICKET_UNAVAILABLE: 'ORDER_TICKET_UNAVAILABLE',
  ORDER_TICKET_SALE_CLOSED: 'ORDER_TICKET_SALE_CLOSED',

  STAFF_ALREADY_ASSIGNED: 'STAFF_ALREADY_ASSIGNED',
  STAFF_INVITE_PENDING_EXISTS: 'STAFF_INVITE_PENDING_EXISTS',
  STAFF_LIMIT_REACHED: 'STAFF_LIMIT_REACHED',
  STAFF_INVITE_INVALID_USER: 'STAFF_INVITE_INVALID_USER',
  STAFF_NOT_ASSIGNED: 'STAFF_NOT_ASSIGNED',
  STAFF_SUBSCRIPTION_REQUIRED: 'STAFF_SUBSCRIPTION_REQUIRED',

  EVENT_NOT_REVIEWABLE: 'EVENT_NOT_REVIEWABLE',
  EVENT_NOT_HIDEABLE: 'EVENT_NOT_HIDEABLE',
  EVENT_HAS_PAID_ORDERS: 'EVENT_HAS_PAID_ORDERS',
  EVENT_NOT_CANCELLABLE: 'EVENT_NOT_CANCELLABLE',

  // System
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};

module.exports = ErrorCodes;
